import Head from 'next/head'
import Footer from '../../organisms/Footer';
import Header from '../../organisms/Header';

interface Props {
  children: React.ReactNode
}
const Layout = ({children}: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className='py-8'>
        {children}
      </main>
      <Footer />
    </>
  )
}
export default Layout;